#
# VM thunks generator
#

# Main target in this dir
TARGET:= \
	vm_gen_thunks \

# What to build from
SOURCES:= \
	vm_gen_thunks.c \

# Include either target or host
include $(SOURCES_ROOT)/Makefile.host.inc

# Additional rules
