#include <stdio.h>
#include <stdint.h>
#include "vm_misc.h"
#include "vm_opcodes.in"
#include "vm_opcodes_traits.h"

int main()
{
	FILE *fd;
	int index;
	
	fprintf(stdout, "Opcode count: %d\n", ARRAY_SIZE(opcodes));
	if (ARRAY_SIZE(opcodes) >= 64) {
		fprintf(stdout, "Too many opcodes: max %d\n", 64);
		return 1;
	}
	
	fprintf(stdout, "Generating vm_opcodes.h.\n");
	fd = fopen("vm_opcodes.h", "w");
	fprintf(fd, "#ifndef __mette_vm_opcodes_h_included\n#define __mette_vm_opcodes_h_included\n\n");
	fprintf(fd, "/* NOTE: AUTOGENERATED FILE. All editions will be discarded. */\n\n");
	fprintf(fd, "typedef enum {\n");
	for (index = 0; index < ARRAY_SIZE(opcodes); ++index) {
		fprintf(fd, "\t/* %s */\n", opcodes[index].description);
		fprintf(fd, "\tVMOP_%s\t\t= 0x%02X, /* %d -> %d */\n",
			opcodes[index].mnemonic, 
			index,
			opcodes[index].stack_in,
			opcodes[index].stack_out);
	}
	fprintf(fd, "} vm_opcode_t;\n\n");
	fprintf(fd, "#endif // __mette_vm_opcodes_h_included\n\n");
	fclose(fd);
	
	fprintf(stdout, "Generating vm_opcodes_switch.tab.\n");
	fd = fopen("vm_opcodes_switch.tab", "w");
	fprintf(fd, "/* NOTE: AUTOGENERATED FILE. All editions will be discarded. */\n\n");
	fprintf(fd, "static const unsigned short offtab[64] = {\n");
	for (index = 0; index < ARRAY_SIZE(opcodes); ++index) {
		if (opcodes[index].mnemonic) {
			fprintf(fd, "\t&&op_%s - &&op_invalid,\n", opcodes[index].mnemonic);
		} else {
			fprintf(fd, "\t0,\n");
		}
	}
	fprintf(fd, "};\n\n");
	fclose(fd);
	
	return 0;
}


