#ifndef __mette_vm_opcodes_h_included
#define __mette_vm_opcodes_h_included

/* NOTE: AUTOGENERATED FILE. All editions will be discarded. */

typedef enum {
	/* Addition */
	VMOP_ADD		= 0x00, /* 2 -> 1 */
	/* Subtraction */
	VMOP_SUB		= 0x01, /* 2 -> 1 */
	/* Multiplication (unsigned*unsigned) */
	VMOP_UMUL		= 0x04, /* 2 -> 2 */
	/* Multiplication (signed*signed) */
	VMOP_SMUL		= 0x05, /* 2 -> 2 */
	/* Division (unsigned/unsigned) */
	VMOP_UDIV		= 0x06, /* 2 -> 2 */
	/* Division (signed/signed) */
	VMOP_SDIV		= 0x07, /* 2 -> 2 */
	/* Bitwise AND */
	VMOP_AND		= 0x10, /* 2 -> 1 */
	/* Bitwise OR */
	VMOP_OR		= 0x11, /* 2 -> 1 */
	/* Bitwise XOR */
	VMOP_XOR		= 0x12, /* 2 -> 1 */
	/* Bitwise NOT */
	VMOP_NOT		= 0x13, /* 2 -> 1 */
	/* Logical shirt left */
	VMOP_LSL		= 0x18, /* 2 -> 1 */
	/* Logical shift right */
	VMOP_LSR		= 0x19, /* 2 -> 1 */
	/* Arithmetic shift right */
	VMOP_ASR		= 0x1A, /* 2 -> 1 */
	/* Compare (less than) */
	VMOP_CC_LT		= 0x40, /* 2 -> 1 */
	/* Compare (greater than) */
	VMOP_CC_GT		= 0x41, /* 2 -> 1 */
	/* Compare (less than or equal) */
	VMOP_CC_LE		= 0x42, /* 2 -> 1 */
	/* Compare (greater than or equal) */
	VMOP_CC_GE		= 0x43, /* 2 -> 1 */
	/* Compare (below) */
	VMOP_CC_B		= 0x44, /* 2 -> 1 */
	/* Compare (above) */
	VMOP_CC_A		= 0x45, /* 2 -> 1 */
	/* Compare (below or equal) */
	VMOP_CC_BE		= 0x46, /* 2 -> 1 */
	/* Compare (above or equal) */
	VMOP_CC_AE		= 0x47, /* 2 -> 1 */
	/* Compare (equal) */
	VMOP_CC_EQ		= 0x48, /* 2 -> 1 */
	/* Compare (not equal) */
	VMOP_CC_NE		= 0x49, /* 2 -> 1 */
	/* Load 0 on the stack */
	VMOP_LDC0		= 0xC0, /* 0 -> 1 */
	/* Load 1 on the stack */
	VMOP_LDC1		= 0xC1, /* 0 -> 1 */
	/* Load 2 on the stack */
	VMOP_LDC2		= 0xC2, /* 0 -> 1 */
	/* Load an unsigned byte on the stack */
	VMOP_LDCU8		= 0xC8, /* 0 -> 1 */
	/* Load a signed byte on the stack */
	VMOP_LDCS8		= 0xC9, /* 0 -> 1 */
	/* Load a 32-bit value on the stack */
	VMOP_LDC32		= 0xCA, /* 0 -> 1 */
	/* Load a 8-bit unsigned from memory */
	VMOP_LDMU8		= 0xD0, /* 1 -> 1 */
	/* Load a 8-bit signed from memory */
	VMOP_LDMS8		= 0xD1, /* 1 -> 1 */
	/* Load a 16-bit unsigned from memory */
	VMOP_LDMU16		= 0xD2, /* 1 -> 1 */
	/* Load a 16-bit signed from memory */
	VMOP_LDMS16		= 0xD3, /* 1 -> 1 */
	/* Load a 32-bit from memory */
	VMOP_LDM32		= 0xD4, /* 1 -> 1 */
	/* Store a 8-bit to memory */
	VMOP_STM8		= 0xD8, /* 2 -> 0 */
	/* Store a 16-bit to memory */
	VMOP_STM16		= 0xD8, /* 2 -> 0 */
	/* Store a 32-bit to memory */
	VMOP_STM32		= 0xD8, /* 2 -> 0 */
	/* Duplicate the topmost entry on the stack */
	VMOP_DUP		= 0xE0, /* 1 -> 2 */
	/* Swap two entries on the top of the stack */
	VMOP_SWAP		= 0xE2, /* 2 -> 2 */
	/* Discard the topmost entry on the stack */
	VMOP_POP		= 0xE8, /* 1 -> 0 */
	/* Branch short (8-bit offset) */
	VMOP_BRS		= 0xF0, /* 0 -> 0 */
	/* Branch long (32-bit offset) */
	VMOP_BRL		= 0xF1, /* 0 -> 0 */
	/* Branch if true (8-bit offset) */
	VMOP_BRT		= 0xF2, /* 1 -> 0 */
	/* Branch if false (8-bit offset) */
	VMOP_BRF		= 0xF3, /* 1 -> 0 */
	/* Call a subroutine (32-bit offset) */
	VMOP_CALL		= 0xF8, /* 0 -> 0 */
	/* Return from the subroutine */
	VMOP_RET		= 0xF9, /* 0 -> 0 */
	/* Call a native subroutine */
	VMOP_NCALL		= 0xFC, /* 0 -> 0 */
} vm_opcode_t;

#endif // __mette_vm_opcodes_h_included

